file.input           = "actin_filament_reference.pdb"
file.output.basename = "actin_filament_2nmpx"
file.output.formats  = ["tsv", "svg"]
probe.size           = {radius = "2.0nm", angle = 10.0}
resolution.x         = "2.0nm"
resolution.y         = "2.0nm"
resolution.z         = "0.64angstrom"
range.x              = ["0.0nm", "80.0nm"]
range.y              = ["0.0nm", "80.0nm"]
scale_bar.length     = "5.0nm"
stage.align          = true
stage.position       = 0.0
noise                = "0.3nm"
